"""create ai advice logs

Revision ID: 874abb5213a8
Revises: 7ebe305db3d6
Create Date: 2026-10-10 11:21:27.418301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874abb5213a8'
down_revision: Union[str, Sequence[str], None] = '7ebe305db3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_advice_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_advice_logs_date'), 'ai_advice_logs', ['date'], unique=False)
    op.create_index(op.f('ix_ai_advice_logs_user_id'), 'ai_advice_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_advice_logs_user_id'), table_name='ai_advice_logs')
    op.drop_index(op.f('ix_ai_advice_logs_date'), table_name='ai_advice_logs')
    op.drop_table('ai_advice_logs')
    # ### end Alembic commands ###
